name: Update Leetcode Stats

# When this workflow should run
on:
  schedule:
    - cron: '0 0 * * *'   # Runs daily at midnight (UTC)
  workflow_dispatch:       # You can also trigger manually

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Update Leetcode stats using ready-made Action
      - name: Update Leetcode Stats
        uses: amitsingh-007/leetcode-stats-action@v2
        with:
          username: SimranKhanna   # <-- Your Leetcode username
          theme: pink              # Cute girly theme
          output: README.md        # Output to your README file

      # Step 3: Commit & push the updated README
      - name: Commit & Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update Leetcode stats automatically 💖" || echo "No changes to commit"
          git push
